/* tslint:disable */
/* eslint-disable */
/**
 * Avalara Shipping Verification only
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AgeVerifyFailureCode {
    NotFound = 'not_found',
    DobUnverifiable = 'dob_unverifiable',
    UnderAge = 'under_age',
    SuspectedFraud = 'suspected_fraud',
    Deceased = 'deceased',
    UnknownError = 'unknown_error'
}

export function AgeVerifyFailureCodeFromJSON(json: any): AgeVerifyFailureCode {
    return AgeVerifyFailureCodeFromJSONTyped(json, false);
}

export function AgeVerifyFailureCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeVerifyFailureCode {
    return json as AgeVerifyFailureCode;
}

export function AgeVerifyFailureCodeToJSON(value?: AgeVerifyFailureCode | null): any {
    return value as any;
}

