/* tslint:disable */
/* eslint-disable */
/**
 * Avalara Shipping Verification only
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface AgeVerifyRequestAddress
 */
export interface AgeVerifyRequestAddress {
    /**
     * 
     * @type {string}
     * @memberof AgeVerifyRequestAddress
     */
    line1?: string;
    /**
     * 
     * @type {string}
     * @memberof AgeVerifyRequestAddress
     */
    city?: string;
    /**
     * The state code of the address.
     * @type {string}
     * @memberof AgeVerifyRequestAddress
     */
    region?: string;
    /**
     * The country code of the address.
     * @type {string}
     * @memberof AgeVerifyRequestAddress
     */
    country?: AgeVerifyRequestAddressCountryEnum;
    /**
     * 
     * @type {string}
     * @memberof AgeVerifyRequestAddress
     */
    postalCode?: string;
}

/**
* @export
* @enum {string}
*/
export enum AgeVerifyRequestAddressCountryEnum {
    Us = 'US',
    Usa = 'USA'
}

export function AgeVerifyRequestAddressFromJSON(json: any): AgeVerifyRequestAddress {
    return AgeVerifyRequestAddressFromJSONTyped(json, false);
}

export function AgeVerifyRequestAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeVerifyRequestAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'line1': !exists(json, 'line1') ? undefined : json['line1'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'region': !exists(json, 'region') ? undefined : json['region'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'postalCode': !exists(json, 'postalCode') ? undefined : json['postalCode'],
    };
}

export function AgeVerifyRequestAddressToJSON(value?: AgeVerifyRequestAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'line1': value.line1,
        'city': value.city,
        'region': value.region,
        'country': value.country,
        'postalCode': value.postalCode,
    };
}
