/* tslint:disable */
/* eslint-disable */
/**
 * Avalara Shipping Verification only
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * The Result of a call to the /ageVerification/verify endpoint.
 * @export
 * @interface AgeVerifyResult
 */
export interface AgeVerifyResult {
    /**
     * Describes whether the individual meets or exceeds the minimum legal drinking age.
     * @type {boolean}
     * @memberof AgeVerifyResult
     */
    isOfAge?: boolean;
    /**
     * A list of failure codes describing why a *false* age determination was made.
     * @type {Array<AgeVerifyResult>}
     * @memberof AgeVerifyResult
     */
    failureCodes?: Array<AgeVerifyResult>;
}



export function AgeVerifyResultFromJSON(json: any): AgeVerifyResult {
    return AgeVerifyResultFromJSONTyped(json, false);
}

export function AgeVerifyResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgeVerifyResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isOfAge': !exists(json, 'isOfAge') ? undefined : json['isOfAge'],
        'failureCodes': !exists(json, 'failureCodes') ? undefined : ((json['failureCodes'] as Array<any>).map(AgeVerifyResultFromJSON)),
    };
}

export function AgeVerifyResultToJSON(value?: AgeVerifyResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isOfAge': value.isOfAge,
        'failureCodes': value.failureCodes === undefined ? undefined : ((value.failureCodes as Array<any>).map(AgeVerifyResultToJSON)),
    };
}
