/* tslint:disable */
/* eslint-disable */
/**
 * foundation
 * Platform foundation consists of services on top of which the Avalara Compliance Cloud platform is built. These services are foundational and provide functionality such as common organization, tenant and user management for the rest of the compliance platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface AppTenants
 */
export interface AppTenants {
    /**
     * Identifier of the tenant record
     * @type {string}
     * @memberof AppTenants
     */
    identifier?: string;
}

export function AppTenantsFromJSON(json: any): AppTenants {
    return AppTenantsFromJSONTyped(json, false);
}

export function AppTenantsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppTenants {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
    };
}

export function AppTenantsToJSON(value?: AppTenants | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
    };
}
