/* tslint:disable */
/* eslint-disable */
/**
 * foundation
 * Platform foundation consists of services on top of which the Avalara Compliance Cloud platform is built. These services are foundational and provide functionality such as common organization, tenant and user management for the rest of the compliance platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * Name of the contact
 * @export
 * @interface ContactName
 */
export interface ContactName {
    /**
     * First Name
     * @type {string}
     * @memberof ContactName
     */
    firstName?: string;
    /**
     * Last Name
     * @type {string}
     * @memberof ContactName
     */
    lastName?: string;
}



export function ContactNameFromJSON(json: any): ContactName {
    return ContactNameFromJSONTyped(json, false);
}

export function ContactNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactName {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
    };
}

export function ContactNameToJSON(value?: ContactName | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'lastName': value.lastName,
    };
}
