/* tslint:disable */
/* eslint-disable */
/**
 * foundation
 * Platform foundation consists of services on top of which the Avalara Compliance Cloud platform is built. These services are foundational and provide functionality such as common organization, tenant and user management for the rest of the compliance platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import {
    Device,
    DeviceFromJSON,
    DeviceFromJSONTyped,
    DeviceToJSON,
} from './Device';

/**
 * 
 * @export
 * @interface DeviceList
 */
export interface DeviceList {
    /**
     * 
     * @type {number}
     * @memberof DeviceList
     */
    recordsetCount?: number;
    /**
     * 
     * @type {string}
     * @memberof DeviceList
     */
    nextLink?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceList
     */
    pageKey?: string;
    /**
     * 
     * @type {Array<Device>}
     * @memberof DeviceList
     */
    items?: Array<Device>;
}



export function DeviceListFromJSON(json: any): DeviceList {
    return DeviceListFromJSONTyped(json, false);
}

export function DeviceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recordsetCount': !exists(json, '@recordsetCount') ? undefined : json['@recordsetCount'],
        'nextLink': !exists(json, '@nextLink') ? undefined : json['@nextLink'],
        'pageKey': !exists(json, 'pageKey') ? undefined : json['pageKey'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(DeviceFromJSON)),
    };
}

export function DeviceListToJSON(value?: DeviceList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@recordsetCount': value.recordsetCount,
        '@nextLink': value.nextLink,
        'pageKey': value.pageKey,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(DeviceToJSON)),
    };
}
