/* tslint:disable */
/* eslint-disable */
/**
 * foundation
 * Platform foundation consists of services on top of which the Avalara Compliance Cloud platform is built. These services are foundational and provide functionality such as common organization, tenant and user management for the rest of the compliance platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface GrantRules
 */
export interface GrantRules {
    /**
     * List of permissions to which the condition applies
     * @type {Array<string>}
     * @memberof GrantRules
     */
    permissions?: Array<string>;
    /**
     * Condition in the form of a filter expression
     * @type {string}
     * @memberof GrantRules
     */
    condition?: string;
}



export function GrantRulesFromJSON(json: any): GrantRules {
    return GrantRulesFromJSONTyped(json, false);
}

export function GrantRulesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrantRules {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'permissions': !exists(json, 'permissions') ? undefined : json['permissions'],
        'condition': !exists(json, 'condition') ? undefined : json['condition'],
    };
}

export function GrantRulesToJSON(value?: GrantRules | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'permissions': value.permissions,
        'condition': value.condition,
    };
}
