/* tslint:disable */
/* eslint-disable */
/**
 * foundation
 * Platform foundation consists of services on top of which the Avalara Compliance Cloud platform is built. These services are foundational and provide functionality such as common organization, tenant and user management for the rest of the compliance platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
import {
    Group,
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
} from './Group';

/**
 * 
 * @export
 * @interface GroupList
 */
export interface GroupList {
    /**
     * 
     * @type {number}
     * @memberof GroupList
     */
    recordsetCount?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupList
     */
    nextLink?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupList
     */
    pageKey?: string;
    /**
     * 
     * @type {Array<Group>}
     * @memberof GroupList
     */
    items?: Array<Group>;
}



export function GroupListFromJSON(json: any): GroupList {
    return GroupListFromJSONTyped(json, false);
}

export function GroupListFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recordsetCount': !exists(json, '@recordsetCount') ? undefined : json['@recordsetCount'],
        'nextLink': !exists(json, '@nextLink') ? undefined : json['@nextLink'],
        'pageKey': !exists(json, 'pageKey') ? undefined : json['pageKey'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(GroupFromJSON)),
    };
}

export function GroupListToJSON(value?: GroupList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@recordsetCount': value.recordsetCount,
        '@nextLink': value.nextLink,
        'pageKey': value.pageKey,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(GroupToJSON)),
    };
}
