/* tslint:disable */
/* eslint-disable */
/**
 * foundation
 * Platform foundation consists of services on top of which the Avalara Compliance Cloud platform is built. These services are foundational and provide functionality such as common organization, tenant and user management for the rest of the compliance platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../../runtime';
/**
 * Meta data associated with this object. This information is automatically inserted by the service.
 * @export
 * @interface InstanceMeta
 */
export interface InstanceMeta {
    /**
     * Date and time information when this object was created
     * @type {Date}
     * @memberof InstanceMeta
     */
    created?: Date;
    /**
     * Id of the user/app that created this object
     * @type {string}
     * @memberof InstanceMeta
     */
    createdBy?: string;
    /**
     * Date and time information when this object was last modified
     * @type {Date}
     * @memberof InstanceMeta
     */
    lastModified?: Date;
    /**
     * Id of the user/app that last modified this object
     * @type {string}
     * @memberof InstanceMeta
     */
    modifiedBy?: string;
    /**
     * The URI of the Resource being returned
     * @type {string}
     * @memberof InstanceMeta
     */
    location?: string;
    /**
     * The version of the resource being returned in Etag format
     * @type {string}
     * @memberof InstanceMeta
     */
    version?: string;
}



export function InstanceMetaFromJSON(json: any): InstanceMeta {
    return InstanceMetaFromJSONTyped(json, false);
}

export function InstanceMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'lastModified': !exists(json, 'lastModified') ? undefined : (new Date(json['lastModified'])),
        'modifiedBy': !exists(json, 'modifiedBy') ? undefined : json['modifiedBy'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function InstanceMetaToJSON(value?: InstanceMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created': value.created === undefined ? undefined : (value.created.toISOString()),
        'createdBy': value.createdBy,
        'lastModified': value.lastModified === undefined ? undefined : (value.lastModified.toISOString()),
        'modifiedBy': value.modifiedBy,
        'location': value.location,
        'version': value.version,
    };
}
